### ISSUE TITLE
Vis client slower than before?

### ISSUE THREAD

**Issue by stolk** [Celtoys/Remotery#102]
is it me, or did the remotery vis client become a lot slower?

I am on Ubuntu 16.04 and use Mozilla to view the viz.
I run the app for 10sec or so, pause the viz client.
I can scroll the timeline, but the viz client is very choppy.
Especially so if I zoom out.
I can even freeze mozilla for 5 or 10 sec with the remotery viewer.

I remember that it used to be smooth and snappy?

**Comment by Celtoys** [comment]
Nothing's changed. Has your driver been black listed? https://wiki.mozilla.org/Blocklisting/Blocked_Graphics_Drivers

**Comment by dwilliamson** [comment]
Fixed with 99e4c4a199936c61fcff8827a557bb5ad5e5545a
