### ISSUE TITLE
Question: Does remotery work with OpenGL ES.

### ISSUE THREAD

**Issue by arjankuijpers** [Celtoys/Remotery#114]
If not, this is a feature request 👍

**Comment by dwilliamson** [comment]
I do not believe ES has `GL_TIMESTAMP` which is what the OpenGL support requires. There is `EXT_disjoint_timer_query` which could potentially be plugged in but from others it appears support is patchy.

I have no clients that need this support and no time or hardware to test an implementation on so I personally won't be able to work on this. However, I'll leave it open for now in case somebody wants to dedicate some time to adding the extension support.

**Comment by arjankuijpers** [comment]
maybe an idea, for someone who is able to work on this feature, you can buy a Raspberry Pi (3).
Which has OpenGL 2.0. handy because its cheap.
