### ISSUE TITLE
Assertion failure error

### ISSUE THREAD

**Issue by Megavoxel01** [Celtoys/Remotery#118]
Hi!
Get another problem when profiling OpenGL.
When calling rmt_BeginOpenGLSample(UnscopedSample) for the second time it causes an assertion failure at line 6145. Any insight on this one?
platform: VS2015, Windows 10.

**Comment by dwilliamson** [comment]
Are your samples balanced correctly? i.e. are there the same number of calls to Push as there are Pop?

**Comment by Megavoxel01** [comment]
Hi!
Do you mean I need to place sample call in pair?
I tried it for another time today but it still didn't work. Here is my code.
`rmt_BindOpenGL();
while(!glfwWindowShouldClose(window)){//My render loop
 {
   ..........
    rmt_BeginOpenGLSample(UnscopedSample);
    //draw call
    rmt_EndOpenGLSample();
 }
  ..........
}
rmt_UnbindOpenGL();`
It works fine in the first frame. But after entering the second frame the program crashes.
I also tried to replace opengl sample call with CPU sample call and it worked fine.
Am I doing anything wrong?

**Comment by dwilliamson** [comment]
No idea what's going on. If you can dig into the problem yourself, that would be very helpful.
