### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by septag** [Celtoys/Remotery#119]
Hi
I've found that my program is leaking memory when using remotery.  
I've monitored the Alloc/free callbacks, there are lots of Allocs and no frees, I guess no "sample nodes" are destroyed after ```_rmt_EndCPUSample``` but they are destroyed after ```DestroyGlobalInstance```.  
I've checked all BeginSamples and they end with a call to EndCPUSample.  
Is there something that I'm doing wrong with the API ?

thanks

**Comment by dwilliamson** [comment]
Remotery uses a constant-time free-list allocator. If there are no samples in the allocator then it will dynamically allocate one via `rmtMalloc`. When the sample is no longer needed it will be placed back in the allocator for use later. `rmtFree` is not called until you destroy the Remotery instance, at which point all memory allocated should be returned back to the system.

With this behaviour, Remotery will require memory for the maximum number of samples active in any one frame.

This is a performance optimisation as the last thing you want a timing inner loop to be doing is calling out to a generic memory allocator on each call.
