### ISSUE TITLE
glFinish blocks infinitely

### ISSUE THREAD

**Issue by RSDuck** [Celtoys/Remotery#129]
Somehow [this call of `glFinish`](https://github.com/Celtoys/Remotery/blob/master/lib/Remotery.c#L6438) results in a hanging application.

Here is a sample which is enough to hang my GPU. Every iteration of this loop needs ~10 seconds.
(it's in Nim, I hope you can understand the meaning anyway)
```nim
for i in 0..<16:
        var timer = GLint64 0
        echo i, ". glFinish"
        glFinish()
        echo i, ". glGet TIMESTAMP"
        glGetInteger64v(GL_TIMESTAMP, addr timer)
```

I know that this is probably a driver issue, but since this happens the first time for me with this library, I considered this would be the best place to start a discussion. 
I'm using a fairly common GPU, an Intel HD 4000 with Windows 10. It's already a rather old card and not the most powerful one, but even today it does a good job.

**Comment by dwilliamson** [comment]
Sorry, I have no idea. Paging @darksylinc as this seems to be a mirror of this code here: https://github.com/Celtoys/Remotery/blob/9257b7b2d3fc9ff6ed6ddfd7b6f03b10a340c4a9/lib/Remotery.c#L6434

**Comment by darksylinc** [comment]
Hi!
Yeah the detail of how that code works is explained here: https://github.com/Celtoys/Remotery/pull/121

Basically this is a synchronization step; as we need to synchronize the CPU and GPU clocks.

But if each iteration of the loop needs ~10 seconds then it's safe to say it's a horrible driver bug (Windows Intel HD 4000 OpenGL drivers are known to be quite buggy), or the Nim programming language (which I haven't heard of until today) is doing something inside in its internals to OpenGL that causes glFinish to malfunction (doubtful).

If each iteration loop takes 10 seconds, then certainly synchronization accuracy is thrown out of the window. My recommendations would be:

- Update your GPU drivers to see if the problem goes away, if you aren't on latest already. Or move to Linux, as the Linux drivers for Intel HD 4000 are still being maintained.
- Define RMT_GPU_CPU_SYNC_NUM_ITERATIONS to 1
- Define RMT_GPU_CPU_SYNC_SECONDS to 0, which means Remotery will never synchronize GPU and CPU clocks. This behavior is as if the pull request never happened, and the GPU and CPU timelines will be independent; but your huge stalls will disappear.
- Try to comment the calls to glFinish. Perhaps it "just works", even though it's not strictly correct.

**Comment by RSDuck** [comment]
>Update your GPU drivers to see if the problem goes away, if you aren't on latest already. Or move to Linux, as the Linux drivers for Intel HD 4000 are still being maintained.
This actually worked! I thought they don't maintain the Windows drivers anymore since maybe 2015. But they actually released occasionally some updates.

Now it works, many thanks both of you! I really should have checked that earlier.
