### ISSUE TITLE
Solution for displaying hash_names instead of names in browser

### ISSUE THREAD

**Issue by Shelim** [Celtoys/Remotery#131]
Hello,

If you happen to run into problem of remotery displaying something like this:
![problem2](https://user-images.githubusercontent.com/4707644/36623408-c7c14ef8-1904-11e8-99df-b45d9a34d6ce.jpg)

look to `Remotery.js` inside `vis/Code` near line 255:

`function OnSampleName`

will repopulate sample names *only* after new sample is recieved. If your thread does not populate samples for some period of time, then hash names will be retained.

**Very crude** solution is to rewrite that function as:

	function OnSampleName(self, socket, data_view)
	{
        // Add any names sent by the server to the local map
	    var data_view_reader = new DataViewReader(data_view, 4);
	    var name_hash = data_view_reader.GetUInt32();
	    var name = data_view_reader.GetString();
	    self.NameMap[name_hash] = name;
		
		for (key of Object.keys(self.SampleWindows))
		{
			var sampleWindow = self.SampleWindows[key];
			var frame_history = self.FrameHistory[key];
			var samples = [];
			for(sample of sampleWindow.Samples)
			{
				if(sample.name_hash == name_hash)
					sample.name = name;
				samples.push(sample);
			}
			sampleWindow.OnSamples(sampleWindow.nb_samples, sampleWindow.SampleDigest, samples);
			self.TimelineWindow.OnSamples(key, frame_history);
		}
	}

It is likely too crude to make as PR through :) But it is working without visible side effects, so someone may find that useful!

**Comment by Celtoys** [comment]
Thanks for opening a PR for this. I have this fixed locally using an extra level of indirection and will push that later when I get some time.

**Comment by Shelim** [comment]
Bump?

**Comment by dwilliamson** [comment]
Apologies, got distracted. Fix is here 012163423db08c606cae9f0d3af85ca7477d4bbb

cc @neo2buha
