### ISSUE TITLE
Uncaught Exception

### ISSUE THREAD

**Issue by Aborres** [Celtoys/Remotery#132]
Hi, suddenly Remotery stopped working showing this error on the console of chrome:

Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
at Object.LocalStore.Get (file:///[...]deps/remotery/vis/extern/BrowserLib/Core/Code/LocalStore.js:20:14)
    at new Remotery (file:///[...]deps/remotery/vis/Code/Remotery.js:52:40)
    at file:[...]deps/remotery/vis/index.html:49:19
LocalStore.Get @ LocalStore.js:20
Remotery @ Remotery.js:52
(anonymous) @ index.html:49

I have tested it in Chrome, Firefox and Edge and it does not appear in any of them. 
I have been looking for similar issues but I have not found anything similar.

Thanks a lot.

**Comment by dwilliamson** [comment]
Have you changed this setting? https://www.chromium.org/for-testers/bug-reporting-guidelines/uncaught-securityerror-failed-to-read-the-localstorage-property-from-window-access-is-denied-for-this-document

**Comment by Aborres** [comment]
That seems to be doing the trick, sorry for the trouble. Thanks again

**Comment by dwilliamson** [comment]
You shouldn't have to sacrifice privacy just to get Remotery running. This change should work with your previous settings: https://github.com/Celtoys/Remotery/commit/c3194eefbed8b120eb6212586f49f142a5983ee1

**Comment by Aborres** [comment]
I have just tested your changes and it seems to be working fine :)
Thanks a lot again
