### ISSUE TITLE
Compilation error C++ (easy fix)

### ISSUE THREAD

**Issue by emilk** [Celtoys/Remotery#133]
Problem:

```
Remotery.c:4806:21: error: no matching function for call to 'Buffer_Write'
                    Buffer_Write(bin_buf, "SSMP", 4);
                    ^~~~~~~~~~~~
Remotery.c:1773:17: note: candidate function not viable: no known conversion from 'const char [5]' to 'void *' for 2nd argument
```

FIx:

`static rmtError Buffer_Write(Buffer* buffer, void* data, rmtU32 length)`
->
`static rmtError Buffer_Write(Buffer* buffer, const void* data, rmtU32 length)`

(PS: thank's for a great library!)

**Comment by dwilliamson** [comment]
Thanks for reporting this? What compiler/OS combination are you using? The CI is building in C++ mode but only for MSVC; I may need to add gcc and clang as well...

**Comment by emilk** [comment]
This was clang/MacOS (I can give you details later if you want; on mobile now)

**Comment by dwilliamson** [comment]
I've just reproduced this with GCC. Really worrying that MSVC was not reporting it but then, what's new...

I'll add a few more test cases to the CI to try and catch more of this in the future. Thanks again.

**Comment by emilk** [comment]
Thanks for the really quick fix!
