### ISSUE TITLE
trace labels can be broken (possibly, when many threads are used)

### ISSUE THREAD

**Issue by alariq** [Celtoys/Remotery#136]
Hi, All

I have a case when trace labels get corrupted. Instead I see random numbers.
![image](https://user-images.githubusercontent.com/2250561/38202178-86b347ba-36a3-11e8-9817-d228e5c93628.png)

In some cases it may fix itself, but mostly not.

**Comment by dwilliamson** [comment]
So this isn't corruption. Sample names are sent to the client as their integer hash, which is what you're seeing. When the client receives a hash it doesn't know the name for it sends a request to the server for the name to be sent.

This will happen slowly over time and if you have a lot of sample names could take a few seconds to complete.

As of last week it also never used to update historical sample names in the sample/timeline views. However, this has been fixed and it looks like you don't have latest (there are no milliseconds counts in the timeline view).

Can you sync to latest and see what this does for you?

**Comment by alariq** [comment]
Hmm, thanks for the clarification. I've version from last Friday or so. I'll get latest and check again tomorrow.
I also think this may be related to the fact that I press PAUSE, right after my function of interest has finished its work. Maybe I should wait a bit, so that all requests would finish... However, I remember that some events that were fired at the very beginning still had hashes instead of names, while some others which were fired later had correct names.

**Comment by dwilliamson** [comment]
Samples that are numbers early in the profile and then change to names later should be fixed in this commit: https://github.com/Celtoys/Remotery/commit/012163423db08c606cae9f0d3af85ca7477d4bbb

If not then you may have found another bug with Pause not pumping the name requests correctly.

**Comment by alariq** [comment]
Ok. I've just checked. I used latest code but not latest visualization part. Now timeline looks ok, though marker trees which are displayed below may still contain hashes. Here is the link 
![image](https://user-images.githubusercontent.com/2250561/38240255-d28460e0-3737-11e8-8cd8-fe1da7cfbcd6.png)

**Comment by dwilliamson** [comment]
If you reselect a `Thread1` root entry in the timeline does it update and refresh the names in the sample view?

**Comment by alariq** [comment]
nope it does not, moreover when I have more threads that can fit timeline without vertical scrollbar (so that scrollbar actually appears) I can only select root entry in timeline (basically selection breaks, esp. when I scroll window to see threads which are at the bottom

**Comment by dwilliamson** [comment]
I don't understand how that can happen as they're rendering from the same list of samples :/

**Comment by alariq** [comment]
Sorry :-) , maybe it is my case, I am using threads heavilly, maybe there is some threading issue...

**Comment by dwilliamson** [comment]
If you can get some extra tests done that would be great; if you could debug it, even better. Meanwhile I'm going to set some time aside to go through the code and try to find any failure cases.

**Comment by dwilliamson** [comment]
This should be fixed with the latest name map changes.
