### ISSUE TITLE
Making the timeline bigger?

### ISSUE THREAD

**Issue by vblanco20-1** [Celtoys/Remotery#142]
Hello.
Im building a program with many threads, and thus many rows in the timeline. but as only a few rows are shown, it needs copious scrolling to work.
Is there a way to make the timeline bigger? I dont mind if its hardcoding a value on the js files.

**Comment by dwilliamson** [comment]
I believe you can change the height here: https://github.com/Celtoys/Remotery/blob/master/vis/Code/TimelineWindow.js#L67

You'll also need to increase the size of the Timeline Container below it: https://github.com/Celtoys/Remotery/blob/master/vis/Code/TimelineWindow.js#L72

Sample windows will auto-resize to match this new height.

**Comment by vblanco20-1** [comment]
Thanks a lot this is exactly what i needed.
