### ISSUE TITLE
Bandwidth issues

### ISSUE THREAD

**Issue by vblanco20-1** [Celtoys/Remotery#144]
Hello.
I have a multithread engine im developing, wich is finely multithreaded with a lot of jobs. I have an issue with the bandwidth of remotery where it just misses a lot of the profile data on the viewer. I have tried to increase the message queue size and max messages per update, but that chokes the viewer into crashing (chrome) and its hard to take a proper capture. 

Is there any recomended things to do for this? I was thinking on what to do to make the traces more viewable.

Given that im limited by bandwidth and size, would it make sense to have my fine grained jobs disabled, and only call remotery events once every X frames or with a key event?

**Comment by dwilliamson** [comment]
Remotery currently doesn't deal well with huge amounts of samples, for many reasons. Some issues you can find related to your problems are:

https://github.com/Celtoys/Remotery/issues/126
https://github.com/Celtoys/Remotery/issues/20
https://github.com/Celtoys/Remotery/issues/19

Once you get that data over, it's repopulating all sample trees which is hugely non-performant. Work on improvements/fixes to all these is ongoing but slow. Any help is hugely appreciated.

Right now it all boils down to sending less data by either reducing the number of samples per frame or by reducing the frequency at which you send samples.
