### ISSUE TITLE
VS2017 precompiled headers

### ISSUE THREAD

**Issue by Selmar** [Celtoys/Remotery#147]
Hey,

I've added remotery to my project to use for profiling. I ran into one issue that I can not solve in a nice way. I think this is more of a VS2017 issue, but I thought I'd mention it anyway:

> ...\remotery\lib\remotery.c : fatal error C1853: 'x64\Debug\SomeSharedLib.pch' precompiled header file is from a previous version of the compiler, or the precompiled header is C++ and you are using it from C (or vice versa)

I think I have tried pretty much everything related to precompiled headers (except for turning them off completely). The only thing that worked was renaming `remotery.c` to `remotery.cpp`. This is obviously not ideal. If anyone happens to have a good idea, I am all ears.

**Comment by gallegretti** [comment]
On the solution explorer, locate the file 'Remotery.c', right click it and open the properties:
Then go to 'Precompiled Headers' and change the option 'Precompiled Header' to 'Not Using Precompiled Headers'. Also, if you are including your PCH it via the 'Forced Include File' setting, remove it from there as well for the Remotery.c file.

**Comment by Selmar** [comment]
I have tried that, it does not work for me.

**Comment by Anton-V-K** [comment]
I would try including `remotery.c` into the source which contains `main`/`WinMain`/`DllMain`, like
```
#include <remotery.h>
#include <remotery.c>
```

**Comment by dwilliamson** [comment]
I am not sure why I never responded to this issue. You will want to use the `/TP` command-line option for compiling C files as C++.

Example in the build script here: https://github.com/Celtoys/Remotery/blob/master/.appveyor.yml#L34

Documentation here: https://docs.microsoft.com/en-us/cpp/build/reference/tc-tp-tc-tp-specify-source-file-type?view=vs-2019

I believe there's an option for this in the fille properties from within the IDE, e.g: 
![image](https://user-images.githubusercontent.com/1532903/80954295-08a8b700-8df5-11ea-9360-e0da252d1f0e.png)

**Comment by AsoboStudio** [comment]
I'm a bit ashamed I didn't find that myself! This works, thank you! 👍

**Comment by Selmar** [comment]
I'm a bit ashamed I didn't find that myself! This works, thank you! 👍
