### ISSUE TITLE
METAL profile problems

### ISSUE THREAD

**Issue by septag** [Celtoys/Remotery#149]
I'm trying to get metal profiler working, but still no success

same code seems to be working in d3d11 and OpenGL. but in metal, the first problem is that I get no profile information in the viewer about metal (unlike other APIs).
And on *rmt_DestroyGlobalInstance*, I get assertion failure on ```ObjectAllocator_Destructor``` : ```assert(allocator->nb_inuse == 0);```

ps. thanks for the great lib

**Comment by dwilliamson** [comment]
Are you calling `rmt_BindMetal` before each Metal sample? Note the Metal API doesn't expose fine-grained event sampling so you can only sample a whole command buffer at a time.

**Comment by septag** [comment]
hm.. didn't know about that, thanks for clarifying this.
