### ISSUE TITLE
GL_TIMESTAMP not supported on OSX

### ISSUE THREAD

**Issue by conversy** [Celtoys/Remotery#171]
Hi,

I can't figure out how to get usable traces from my OpenGL application, even if I follow the description in readme.md.
Incidentally, I use glad as a crossplatform OpenGL functions loader, it might be the reason why I see nothing useful reported by remotery.

So, could it be my use of glad? If so, I could give a try at understanding how it's supposed to work and provide a PR for glad support.
Or should I use OpenGL Query objects explicitly in my app?
In this case, would it be possible to add a sample, or link to an existing example somewhere to understand how it is supposed to work?

Best.

**Comment by dwilliamson** [comment]
Which platform is this?

If you take a look at `_rmt_BindOpenGL` you can see which module it loads your GL functions from. If these are different to the ones that GLAD is getting your function pointers from then it won't work.

**Comment by conversy** [comment]
sorry: MacOS
It seems to be loading the correct functions, or at least the pointers are not null.

**Comment by dwilliamson** [comment]
That will be `/System/Library/Frameworks/OpenGL.framework/Versions/Current/OpenGL` then.

Checking that the pointers are not null won't discover the problem: they will both load

I can't recall how this works in XCode but usually when you get a function pointer in VSDbg it also tells you which DLL it comes from:

![image](https://user-images.githubusercontent.com/1532903/107496635-773b5200-6b89-11eb-802d-fe24bf037160.png)

If you can't tell which DLL they come from then you can compare addresses from any two GL functions.

**Comment by dwilliamson** [comment]
A further place to find out is the GLAD source:

https://github.com/Dav1dde/glad/blob/b5d260b65b3edbbd9e75f5a6c9924fe0ff4f04dd/glad/lang/c/loader/__init__.py#L65-L83

Note it searches 3 frameworks before it gets to the one Remotery uses.

**Comment by conversy** [comment]
It's even more complicated by the fact that I pass a GL function loader to glad when initing it.
In my case this is SDL_GL_GetProcAddress. I guess that all those functions eventually load functions from the standard MacOS OpenGL library, #4 in the glad sources you found (/System/Library/Frameworks/OpenGL.framework/Versions/Current/OpenGL) (on my system, #3 is a link to #4).

Maybe the first thing would be for me to understand what I should expect from the Remotery viewer.
For example, I have this code in my base:
rmt_BeginOpenGLSample(trp_gl);
trp.gl(current_context()); // <- this is a method that will call a bunch of opengl functions
rmt_EndOpenGLSample();

In the Remotery viewer, I can see a new window (Thread2 (OpenGL))with multiple samples entitled "trp_gl" with all times set to 0.000.
Is it what is expected?
Is there something else I should do to have more information?

Thx for you help.

**Comment by dwilliamson** [comment]
Ah, OK, yes, there's a big problem here: OSX stopped supported `GL_TIMESTAMP` a few years back so it will just return zero for you.

So everything is working "as expected" unfortunately.

See this thread here for an initial discussion: https://www.mail-archive.com/mac-opengl@lists.apple.com/msg00001.html

There seems to be some discussion about `GL_TIME_ELAPSED` or `GL_TIME_ELAPSED_EXT` potentially working.

A supposedly working MPV patch can be found here: https://github.com/mpv-player/mpv/issues/4721

Unfortunately I haven't got the time or hardware to test this anymore.

**Comment by conversy** [comment]
AFAIU, for this to work would require Remotery to query elasped time (a delta, GL_TIME_ELAPSED) as opposed to querying  the absolute GPU clock (GL_TIMESTAMP).
I gave it a try, and I seem to kind of making something work. I'm not quite sure about SyncOpenGLCpuGpuTimes and the final computation of start and end, but this would resemble something like this: 

@@ -6780,7 +6781,8 @@ static void OpenGLTimestamp_Begin(OpenGLTimestamp* stamp)
     // First query
     assert(g_Remotery != NULL);
     stamp->cpu_timestamp = usTimer_Get(&g_Remotery->timer);
-    rmtglQueryCounter(stamp->queries[0], GL_TIMESTAMP);
+    rmtglBeginQuery(GL_TIME_ELAPSED, stamp->queries[0]); CHKGL;
+    //rmtglQueryCounter(stamp->queries[0], GL_TIMESTAMP);
 }
 
 
@@ -6790,7 +6792,8 @@ static void OpenGLTimestamp_End(OpenGLTimestamp* stamp)
 
     // Second query
     assert(g_Remotery != NULL);
-    rmtglQueryCounter(stamp->queries[1], GL_TIMESTAMP);
+    rmtglEndQuery(GL_TIME_ELAPSED); CHKGL;
+    //rmtglQueryCounter(stamp->queries[1], GL_TIMESTAMP);
 }
 
 static rmtBool OpenGLTimestamp_GetData(OpenGLTimestamp* stamp, rmtU64* out_start, rmtU64* out_end, rmtU64* out_first_timestamp, rmtU64* out_last_resync)
@@ -6805,25 +6808,29 @@ static rmtBool OpenGLTimestamp_GetData(OpenGLTimestamp* stamp, rmtU64* out_start
 
     // Check to see if all queries are ready
     // If any fail to arrive, wait until later
-    rmtglGetQueryObjectiv(stamp->queries[0], GL_QUERY_RESULT_AVAILABLE, &startAvailable);
+    rmtglGetQueryObjectiv(stamp->queries[0], GL_QUERY_RESULT_AVAILABLE, &startAvailable); CHKGL;
     if (!startAvailable)
         return RMT_FALSE;
-    rmtglGetQueryObjectiv(stamp->queries[1], GL_QUERY_RESULT_AVAILABLE, &endAvailable);
-    if (!endAvailable)
-        return RMT_FALSE;
+    // rmtglGetQueryObjectiv(stamp->queries[1], GL_QUERY_RESULT_AVAILABLE, &endAvailable);
+    // if (!endAvailable)
+    //     return RMT_FALSE;
 
-    rmtglGetQueryObjectui64v(stamp->queries[0], GL_QUERY_RESULT, &start);
-    rmtglGetQueryObjectui64v(stamp->queries[1], GL_QUERY_RESULT, &end);
+    rmtglGetQueryObjectui64v(stamp->queries[0], GL_QUERY_RESULT, &start); CHKGL;
+    //fprintf(stderr,"duration: %lld\n", start);
+    //rmtglGetQueryObjectui64v(stamp->queries[1], GL_QUERY_RESULT, &end);
 
     // Mark the first timestamp. We may resync if we detect the GPU timestamp is in the
     // past (i.e. happened before the CPU command) since it should be impossible.
-    assert(out_first_timestamp != NULL);
-    if (*out_first_timestamp == 0 || ((start - *out_first_timestamp) / 1000ULL) < stamp->cpu_timestamp)
-        SyncOpenGLCpuGpuTimes(out_first_timestamp, out_last_resync);
+    // assert(out_first_timestamp != NULL);
+    // if (*out_first_timestamp == 0 || ((start - *out_first_timestamp) / 1000ULL) < stamp->cpu_timestamp)
+    //      SyncOpenGLCpuGpuTimes(out_first_timestamp, out_last_resync);
 
     // Calculate start and end timestamps (we want us, the queries give us ns)
-    *out_start = (rmtU64)(start - *out_first_timestamp) / 1000ULL;
-    *out_end = (rmtU64)(end - *out_first_timestamp) / 1000ULL;
+    //*out_start = (rmtU64)(start - *out_first_timestamp) / 1000ULL;
+    //*out_end = (rmtU64)(end - *out_first_timestamp) / 1000ULL;
+    *out_start = (rmtU64)(stamp->cpu_timestamp);
+    *out_end = (rmtU64)( (start / 1000ULL) + stamp->cpu_timestamp);
+

**Comment by dwilliamson** [comment]
The implications of this are quite large:

* As we don't have a start time for `GL_TIME_ELAPSED` queries, we can't lay them out in a timeline; we can only calculate a duration for a sample block.
* You're not allowed to nest `GL_TIME_ELAPSED` queries.

This makes them a little useless compared to the other GPU solutions (although Metal is similarly limited by only command-buffer querying).

There is a way I can see this being possible:

* We can measure a start offset from the beginning of the frame by always inserting "empty" queries where the user doesn't request any. So if the user only inserts one sample block per frame, somewhere in the middle, Remotery auto-inserts two more sample blocks on either side to consume the whole frame.
* Nesting can be achieved by runtime-flattening the tree and summing siblings on the CPU during tree reconstruction.

Sounds like an involved chunk of work and it still needs a solution for aligning the GPU times with CPU times. However, this would be highly useful even without that.

**Comment by dwilliamson** [comment]
OK, I've done a little bit more reading and I'm tempted to close this.

Apple made the decision to deprecate OpenGL on their platforms and many years earlier, `GL_TIMESTAMP` was hobbled because it didn't align with their hardware, which was mostly tile-based.

There is potentially no way my above attempt to fix this issue with `GL_TIME_ELAPSED` can work in practice because I think GL queries can't interleave: so inserting timing queries may impact your ability to insert your own occlusion queries.

I do not know if this is true right now and need to do more reading when I get the time.

However, even with that, if the GPU decides to run some of your commands async in some way and you have elapsed timers on them, the sum-from-start-frame approach will break.

The only suggestions I have right now are:

* Use Metal with Remotery on OSX/iOS if you want profile, as supported by Apple.
* Add a separate path to Remotery's GL/OSX code that calls `GL_TIME_ELAPSED` and simply stacks them next to each other in the timeline: you'll get feedback on how long they took but no measure of where they started in the frame.
* Run your own `GL_TIME_ELAPSED` queries outside of Remotery and display the results somewhere else.

**Comment by conversy** [comment]
Thank you very much. I have access to other platforms (Linux, Windows), I may try them and profile my app on them. That would be enough for my use-case.
Again, thank you for your support and your suggestions.

**Comment by dwilliamson** [comment]
Closing for now: supporting a deprecated platform API doesn't seem a good use of time right now.
