### ISSUE TITLE
Modified sample.c crashing after a few seconds - Assertion failed: (sample != tree->root)

### ISSUE THREAD

**Issue by coastwise** [Celtoys/Remotery#176]
I'm having trouble integrating Remotery into my project. It seems to run correctly for a few seconds at least (sometimes up to a minute or so) before it throws an assert.
I have been able to reproduce the behaviour in the provided sample.c code by [changing the initialization of 'end' to 100000](https://github.com/Celtoys/Remotery/files/6424832/sample_assert.patch.txt). This makes 'delay' take between 5 and 20 ms on my 11 year old MacBook Pro (macOS 10.13.6). This seems like a reasonable duration for a "frame", but maybe I need to modify the default Remotery configuration settings to support that frequency? I haven't dug too deeply into what is actually going wrong TBH.

`Assertion failed: (sample != tree->root), function SampleTree_Pop, file lib/Remotery.c, line 4657.`

This screenshot of the visualizer suggests to me that something is going wrong with how the Begin/End are being paired up.
![Screen Shot 2021-05-04 at 10 27 16 PM](https://user-images.githubusercontent.com/239493/117091050-18b8e680-ad28-11eb-9e7e-48e15721802d.png)

I have also seen another assert on a different run of the same modified sample.c:
`Assertion failed: (allocator->first_free != NULL), function ObjectAllocator_Pop, file lib/Remotery.c, line 2156.`

**Comment by dwilliamson** [comment]
This looks like the new long-sample detection code. I will check this out in the next couple of days, thanks.

If all else fails, I'll upload my code to disable that in the settings.

**Comment by dwilliamson** [comment]
Actually, scratch that, can you get latest and try setting `enableThreadSampler = RMT_FALSE` in your settings.

**Comment by coastwise** [comment]
Thanks! Unfortunately, I'm still getting the same '(sample != tree->root)' assert with this [modified sample.c](https://github.com/Celtoys/Remotery/files/6430764/threadsamplerdisabled.patch.txt)

**Comment by dwilliamson** [comment]
OK, that's kind of good news. I will try and test this before the weekend.

Note the sample is not really representative of the load Remotery will undergo in simulations/games and oddly tends to find bugs faster than actual use in the real world. This isn't an issue right now in the games Remotery is powering so you may find it all just works for whatever you need it to.

**Comment by dwilliamson** [comment]
I can't repro this with the patch.

Your report shows being/end clearly not getting paired and the assert mirrors that.

I have no more access to a Mac machine to test this, unfortunately.
