### ISSUE TITLE
Asseret failure on linux

### ISSUE THREAD

**Issue by septag** [Celtoys/Remotery#179]
with the new thread profiler update, I get assert failure everytime I run the program in linux.
I removed all of my own samples, but this still happens with the internal remotery samples after a while (2-3 secs):

![image](https://user-images.githubusercontent.com/5081921/121556017-ca2bf580-ca13-11eb-98c9-4ff79cbc1713.png)

It happens [here](https://github.com/Celtoys/Remotery/blob/92c65e807720a12f3a75b9706a5f84ea125c7c6a/lib/Remotery.c#L4667) when it checks that sample should not be root node.

I also disabled thread sampler (`enableThreadSampler = false`) because of previous regression bugs it introduced to my code.

**Comment by erikogenvik** [comment]
I'm thinking that this might be something that could be fixed by https://github.com/Celtoys/Remotery/pull/181

**Comment by dwilliamson** [comment]
Fixed by #181.
