### ISSUE TITLE
Might I suggest making releases?

### ISSUE THREAD

**Issue by JCash** [Celtoys/Remotery#188]
I think it's beneficial for us using the library to keep track of the major/minor changes.

(ps. thanks for the great library!)

**Comment by dwilliamson** [comment]
I can do that. Give me a ping in 2 weeks if I forget :)

**Comment by YarikTH** [comment]
Ping

**Comment by dwilliamson** [comment]
https://github.com/Celtoys/Remotery/releases/tag/v1.0.0
