### ISSUE TITLE
Unit tests failing

### ISSUE THREAD

**Issue by JCash** [Celtoys/Remotery#196]
It would be good to get the unit tests up and running again.
That way we can add more build configurations for Win/macOS/Linux etc.

**Comment by JCash** [comment]
I have a PR coming up with support for Github Actions.

Using it it seems the main branch has does not build due to the new `rmtTryNew()`

**Comment by JCash** [comment]
Another new warning is this, when building for x86_64 macOS:

```
lib/Remotery.c:1695:12: warning: cast to smaller integer type 'rmtThreadId' (aka 'unsigned int') from 'pthread_t _Nonnull' (aka 'struct _opaque_pthread_t *') [-Wpointer-to-int-cast]
    return (rmtThreadId)pthread_self();
```

**Comment by dwilliamson** [comment]
I've just had issues with that on Windows 64-bit builds.

The `pthread_t` problem may need a better solution on POSIX as there is nothing about `pthread_t` that can't be reused between subsequent threads.

**Comment by dwilliamson** [comment]
`rmtTryNew` is going to need a GCC/Clang fix, I think it's the empty `__VA_ARGS__` issue that needs an extra macro indirection.

**Comment by dwilliamson** [comment]
Can we move the [scripts](https://github.com/Celtoys/Remotery/tree/main/scripts) folder into [.github/workflows](https://github.com/Celtoys/Remotery/tree/main/.github/workflows)? I want to keep the root as clean as possible.
