### ISSUE TITLE
Q: Api for rmt_PropertyExtern?

### ISSUE THREAD

**Issue by JCash** [Celtoys/Remotery#209]
Looking at the current api for `rmt_PropertyExtern`, it seems a bit odd given that we have an internal property type.
What should the `type` be here`?

```
#define rmt_PropertyExtern(type, name) extern rmtProperty name;
```

I just want to clarify before adding a PR for this 🤔

**Comment by dwilliamson** [comment]
Yes, that is weird. Should just be `name`.
