### ISSUE TITLE
Remove AppVeyor integration?

### ISSUE THREAD

**Issue by JCash** [Celtoys/Remotery#212]
Although the repo uses Github Actions, the commits still looks "red" due to the failing AppVeyor tests.
I'm guessing it's a setup on the repo itself?

<img width="821" alt="Screenshot 2022-06-01 at 11 31 49" src="https://user-images.githubusercontent.com/1349334/171374206-f3168bc1-1bff-4664-af5b-c64a6d885618.png">

**Comment by dwilliamson** [comment]
I tried this last night. I'm hoping the next commit won't have the X anymore.

**Comment by dwilliamson** [comment]
Issue here https://github.com/appveyor/ci/issues/3585
