### ISSUE TITLE
[DX12] where/when should I call rmt_MarkFrame()?

### ISSUE THREAD

**Issue by yhyu13** [Celtoys/Remotery#217]
Hi, I am having trouble understanding rmt_MarkFrame() for DX12:

Is rmt_MarkFrame() called internally by remotery anywhere coz I couldn't find any. 

Since it is required that no GPU sampling begin before it and end after it, I have to know where/when it is invoked in a single frame. Or is it totally controlled by us users?

 Is there any best practice to where/when to invoke rmt_MarkFrame(), begining of next frame or the end of current frame?

Thanks~!

**Comment by dwilliamson** [comment]
You call `rmt_MarkFrame` yourself. If your engine has its own concept of `BeginFrame`/`EndFrame` then it's best to place it right before your `EndFrame` when you can guarantee your engine has no open Remotery GPU samples.
