### ISSUE TITLE
Font issue on macOS in version 1.2

### ISSUE THREAD

**Issue by JCash** [Celtoys/Remotery#218]
With the new version, the font in the samples windows is not very readable.

<img width="413" alt="Screenshot 2022-06-30 at 08 33 04" src="https://user-images.githubusercontent.com/1349334/176608688-8894b6e3-80fe-4bea-9ead-557c3461eb4b.png">

**Comment by dwilliamson** [comment]
Can you see if 8e2bfd4e833da035e23578e70ea802ad89ae8b87 fixes it? I've switched to Fira Code on all platforms as it comes with Remotery.

**Comment by JCash** [comment]
I can confirm that the issue is now fixed!
Thanks!

**Comment by JCash** [comment]
Just to show the result. It is a little bit blurry compared to the header font that is crisp:
<img width="412" alt="Screenshot 2022-07-02 at 09 42 25" src="https://user-images.githubusercontent.com/1349334/176991705-d81e966a-a30c-4911-aa69-5b8d9adcae08.png">
