### ISSUE TITLE
Apps targeting Android 10 cannot directly use ashmem (/dev/ashmem)

### ISSUE THREAD

**Issue by AGulev** [Celtoys/Remotery#223]
Android 10 and higher can't use `/dev/ashmem` directly anymore and must use NDK's `ASharedMemory` class.
Because of that Remotery doesn't work on Android 10+.

More info is available here:
https://stackoverflow.com/a/53062250

**Comment by JCash** [comment]
The new Android api does seem to still use the `ashmem_create_region() [internally](https://android.googlesource.com/platform/frameworks/base/+/refs/heads/master/native/android/sharedmem.cpp#53), but it is a lot more involved, and it currently uses `std::string` for I/O:
https://android.googlesource.com/platform/system/core/+/refs/heads/master/libcutils/ashmem-dev.cpp#365

Perhaps dynamically loading the shared library and grabbing the function pointer might be an option 🤔

**Comment by AGulev** [comment]
Yes,
This is how google chromium does that
https://chromium.googlesource.com/chromium/src/+/refs/heads/main/base/android/linker/modern_linker_jni.cc#186
