### ISSUE TITLE
Complie Error:  `TIMERR_NOERROR` not found when complie under windows 11

### ISSUE THREAD

**Issue by hhhxiao** [Celtoys/Remotery#229]
I can't compile Remotey directly under windows 11, and the error is Identifier  `TIMERR_NOERROR` not found
After I add the follow in the source code, it compiles successfully.
```cpp
#include <Windows.h>
#include <timeapi.h>
```
I'm not sure if this is a problem with the code, but I filed this issue anyway.

**Comment by dwilliamson** [comment]
Thanks. This is already being tracked in https://github.com/Celtoys/Remotery/issues/172
