### ISSUE TITLE
GetInt64 and GetUInt64 return float64

### ISSUE THREAD

**Issue by dsuntsov-ms** [Celtoys/Remotery#235]
This really confused when I tried to code Remotery receiver in Python

```
    DataViewReader.prototype.GetInt64 = function ()
    {
        var v = this.DataView.getFloat64(this.Offset, true);
        this.Offset += 8;
        return v;
    }

    DataViewReader.prototype.GetUInt64 = function ()
    {
        var v = this.DataView.getFloat64(this.Offset, true);
        this.Offset += 8;
        return v;
    }
```

**Comment by dwilliamson** [comment]
What is the issue you are having, exactly? Javascript `DataView` does not support 64-bit integers as the language supports only `numbers`, which are 64-bit floats.

**Comment by dsuntsov-ms** [comment]
> What is the issue you are having, exactly? Javascript `DataView` does not support 64-bit integers as the language supports only `numbers`, which are 64-bit floats.

Just naming issue. Three the same functions with different names.

**Comment by dwilliamson** [comment]
Yeah, that is to allow the caller to specify intent, despite them being implemented exactly the same in the background.
