### ISSUE TITLE
Feature request: split into sampler and separate 'viewer' backends

### ISSUE THREAD

**Issue by dougbinks** [Celtoys/Remotery#3]
Various viewer backends would be useful, so I would propose that separating out the webserver from the sampler would be a good way to make a simple expendable system.

Examples of potentially useful backends:
- Webserver (current backend)
- Binary network server (similar to current but using binary for external C++ viewer)
- In app graphics viewer (using https://github.com/dougbinks/nanovg for example)
- Dump to file

**Comment by red1939** [comment]
Any update on this (especially dumping to file and reading the content in html viewer)? I would start hacking it myself, but I don't want to waste time on doing something that is already done.

**Comment by dwilliamson** [comment]
There is no priority on this right now. Main goal is binary serialisation as there's a lot of titles using this that are bottlenecked by the network transfer.

Even if you do end up hacking this yourself, if you made it public then it's something we can all learn from.

**Comment by dwilliamson** [comment]
Binary network transport has just landed and I'm thinking of simply exposing the protocol to a registered handler to neatly solve this one.

**Comment by dwilliamson** [comment]
Saving/Loading of Remotery traces has recently been added and that's the furthest I intend to take this issue for now.
