### ISSUE TITLE
Add a Stats Graph Window

### ISSUE THREAD

**Issue by Ziflin** [Celtoys/Remotery#32]
One thing that we've used in the past is a 'Stats' window that would show _per-frame_ things like FPS, Active Entities, Draw Call Count, Memory Usage, etc. as just a simple list.  It would be _very_ cool if Remotery had a way to do this and show a small history graph (60 frames worth maybe) of selected stats. Something similar to the Windows 8 Task Manager "Performance" Tab (left side).

Is this something that sounds doable? We are just now starting to look over the source.

**Comment by dwilliamson** [comment]
Yes, that's the plan.

The basic idea is to add unique windows for any hierarchical collection of stats you want. After that I'll then add a graph that you can drag and drop any stat you want onto; this includes any of the sample timings that are currently being recorded.

Are more complete idea I've been toying with is interleaving the stats with the sample call stack you generate in a 2D grid view. So let's say the x-axis represents render stats, like draw calls, shader switches, texture sets, etc; and the y-axis would be your sample call stack. You could go all the way to the root and see that there's N draw calls total per frame, or inspect a single function call and see that it's responsible for generating M draw calls per frame.

**Comment by Ziflin** [comment]
Nice! Sounds very awesome.  Looking forward to getting it integrated.

**Comment by nickkorn** [comment]
Do you have any timeline for the stats graph? Is this anything I could start helping you out with?

**Comment by dwilliamson** [comment]
I'm looking into this in March as I have a new contract that will benefit from it. 

The main issue is coming up with a simple API that isn't too obstructive to adding property tweakers in a later version. So any ideas on what you think that API should look like or be capable of would help.

**Comment by nickkorn** [comment]
For starters I would just be looking for something like: rmt_Stat( "My Stat", value )

**Comment by dwilliamson** [comment]
Will open a new issue for graphs as stats are now done.
