### ISSUE TITLE
Advice on too many threads in Timeline window

### ISSUE THREAD

**Issue by floooh** [Celtoys/Remotery#51]
Hi,

There doesn't seem to be a way to resize or scroll the content of the Timeline window (or is there?). We have a relatively high number of (IO) threads, more then fit into Timeline window which makes it impossible to view or select some thread timelines. My current solution would be to locally hack the visualizer webpage but I'm wondering whether there is a better way to do this, or how much effort it would be to make the timeline window resizable or vertically scrollable.

This is what it looks like:

![remotery_too_many_threads](https://cloud.githubusercontent.com/assets/1699414/8651405/ea512cd2-2978-11e5-9f36-6c4a3d439268.png)

Cheers,
-Floh.

**Comment by dwilliamson** [comment]
I think for now the only reasonable work-around is to add a mouse-wheel scroll to it.

The [timeline window](https://github.com/Celtoys/Remotery/blob/master/vis/Code/TimelineWindow.js) already reacts to mouse scroll events and allows you to zoom in/out of the sample view. Maybe do a check for whether the control key is held down or not and modify the `scrollTop` property of `this.TimelineContainer.Node`. So:

* ctrl+scroll = zoom in/out
* scroll = move up/down

The [tree view control](https://github.com/Celtoys/Remotery/blob/master/vis/extern/BrowserLib/WindowManager/Code/Treeview.js#L235) has an example of how to scroll the window on reaction to a mouse-scroll event.

**Comment by floooh** [comment]
Ok I'll try that, thanks a lot :)

**Comment by floooh** [comment]
After a bit of trial-and-error I ended up using a normal vertical scrollbar int he timeline window, and I'm actually quite happy with this, even though it doesn't look quite as stylish ;)

It looks like this:
![remotery-vscroll](https://cloud.githubusercontent.com/assets/1699414/8674990/a83ccf30-2a41-11e5-8f37-dcf27836a7ba.png)

...and is implemented like this:
https://github.com/floooh/Remotery/commit/8aea3bf02539bb58882fdbd520d54752278f7c7a

I'm really looking forward to the window manager improvements :)

**Comment by dwilliamson** [comment]
Ooo! I was afraid that would look too rubbish but it doesn't look too bad.

I'll have to try that on the sample windows...

**Comment by dwilliamson** [comment]
Can I have a pull request for that?

**Comment by floooh** [comment]
Of course :) https://github.com/Celtoys/Remotery/pull/52
