### ISSUE TITLE
Remotery interface cannot currently be used in a shared library

### ISSUE THREAD

**Issue by dougbinks** [Celtoys/Remotery#56]
I'd like to be able to use remotery in a shared library, and am prepared to do the work to add exporting functions but would like to know if this was something which you'd be prepared to accept a pull request for this?

Additionally if you have any guidelines let me know, otherwise I'll just try to follow the current code style.

**Comment by dwilliamson** [comment]
Yes, it would be good.

I like the way imgui achieves this by having a separate `imconfig.h` file where you can specify the API macro [IMGUI_API](https://github.com/ocornut/imgui/blob/master/imconfig.h#L13). The config file gets included [at the top](https://github.com/ocornut/imgui/blob/master/imgui.h#L10) of `imgui.h` and the macro gets [set to nothing](https://github.com/ocornut/imgui/blob/master/imgui.h#L27) if the user doesn't set it.

This gets around the complexities of having to set this up cross-platform in the library itself. It also lets your declarations be more specific; for example, mine is:

```
#ifndef __clcpp_parse__
	#define IMGUI_DLL
#endif

#ifdef IMGUI_DLL
	#ifdef IMGUI_IMPL
		#define IMGUI_API __declspec(dllexport)
	#else
		#define IMGUI_API __declspec(dllimport)
	#endif
#endif
```

Such a solution would also provide a convenient place for [these config macros](https://github.com/Celtoys/Remotery/blob/master/lib/Remotery.h#L45).

However, I'm note entirely convinced of the part of `IMGUI_API` that sets it to empty if it's not defined, in `imgui.h`. Might as well just set it to empty by default in `imconfig.h` to start with and let the user override it.

**Comment by dwilliamson** [comment]
It's worth mentioning that if you have Remotery in a static library already, it can be used by shared libraries that link to it.  After your initialise Remotery, just pass the global pointer to each DLL that needs it and get the DLL to call [rmt_SetGlobalInstance](https://github.com/Celtoys/Remotery/blob/master/lib/Remotery.h#L248)

**Comment by dougbinks** [comment]
rmt_setGlobalInstance  was the method I'd use if I couldn't use a DLL approach, though I think there is a change needed as the settings are not part of the global remotery instance which could cause problems.

For my use the rmt_setGlobalInstance method is slightly awkward as loading code at runtime means I'd end up calling this in the init of every file.

For the DLL config, the imgui approach is reasonable - by defining IMGUI_DISABLE_INCLUDE_IMCONFIG_H you can use build configuration and avoid needing to change a file in an external project, though I'd be tempted to add an imconfig_user.h file include when IMGUI_INCLUDE_IMCONFIG_USER_H is defined so that users could have their own file on another path. I'll start an implementation on a branch and get back to you for changes.

**Comment by dwilliamson** [comment]
Yes, settings need to be applied per DLL - that's not mentioned anywhere in the header files. I guess the settings API needs to be reworked slightly so that they're inside the Remotery object. But that gets created after the settings are modified typically.

I've half a mind to get rid of `rmt_CreateGlobalInstance` altogether and add something like `rmt_InitGlobalInstance` and `rmt_GetGlobalInstance`.

I think for now the 'RemoteryConfig.h' approach is simple enough to not confuse anybody. I can't foresee merges being too much of any issue downstream as the `RemoteryConfig.h` should contain nothing but documentation comments, so:

```c
// Remotery.h
#include "RemoteryConfig.h"
#ifndef MACRO
#define MACRO default_value
#endif

// RemoteryConfig.h
#define MACRO user_value
```

**Comment by dougbinks** [comment]
I've made a pull request for the changes needed in #57.

Note that this hasn't added the suggested RemoteryConfig.h, as doing so would need splitting out the current configs in a way which looked like it would be a potentially breaking change.
