### ISSUE TITLE
Memory Usage

### ISSUE THREAD

**Issue by jswigart** [Celtoys/Remotery#58]
It appears that if you leave an application running for hours with Remotery enabled, memory will steadily increase and ultimately crash your program.

Does it retain sample data indefinitely?

**Comment by dwilliamson** [comment]
Sample data is discarded after it's sent across the network. Sample allocation is done with an O(1) thread-safe fixed allocator that only malloc's when there are no free samples left. After you account for GPU latency and network performance, there should be a high water mark of use that Remotery eventually settles on.

There are 3 allocators: 1 for samples, 1 for D3D time stamps and 1 for OpenGL time stamps.

If you put a breakpoint on the `rmtMalloc` call in `ObjectAllocator_Alloc` it should eventually stop triggering. If it doesn't, the callstack will tell you where it's coming from.

Do you perhaps have an unbalanced tree that doesn't use scoped samples somewhere?

**Comment by jswigart** [comment]
That's the problem I guess. If you don't have the web page up while running your remotery code it basically builds up memory until it crashes. I would think it would keep a maximum time history or something to avoid that. Not sure how much value there is to opening the web page and then getting flooded by tens of minutes or even hours worth of old sampling history.

**Comment by dwilliamson** [comment]
That would be of no value if indeed that's what Remotery was doing.

Inbetween your thread and the server thread there is a MpSc ring buffer that completed sample trees get pushed to. If the server has no connected web client then it will simply [not consume messages in the queue](https://github.com/Celtoys/Remotery/blob/master/lib/Remotery.c#L3977). Eventually the queue becomes full and your sampling threads will [discard/free sample trees they fail to push onto the queue](https://github.com/Celtoys/Remotery/blob/master/lib/Remotery.c#L3625).

Given that the size of the default queue is [64k](https://github.com/Celtoys/Remotery/blob/master/lib/Remotery.c#L4295) and the size of a sample tree message is 24 bytes, you're looking at Remotery allocating a max of roughly 2500 frames of sample data when not connected.

Have you looked for an unbalanced sample tree?

**Comment by dwilliamson** [comment]
Can't repro.

Behaviour by-design is to not constantly malloc over time whether a client is connected or not.
