### ISSUE TITLE
Doesn't build on Linux with RTM_USE_OPENGL

### ISSUE THREAD

**Issue by DanielGibson** [Celtoys/Remotery#59]
It doesn't build out of the box, I had to do a few changes in Remotery.c:
* around Line 5348 it'll explode because `WINGDIAPI` is unknown. so it should really be an `#elif defined(_WIN32)` case + there needs to be a new #else case with `#define GLAPI extern` or something like that.
* `glXGetProcAddressARB` couldn't be found. `#include <gl/glx.h>` create conflicts with your own GLuint typedefs etc, just adding `extern void* glXGetProcAddressARB(const GLubyte*);` made it work.. not pretty, though

And sometimes I get segfaults on startup
```
Program received signal SIGSEGV, Segmentation fault.
Remotery_Destructor (rmt=0xe78750) at ../Libs/Remotery/Remotery.c:4182
4182	        Delete(OpenGL, rmt->opengl);
```
can't reproduce that reliably though and last time I forgot to get a backtrace :-/

Anyway, thanks for this awesome tool, I really enjoy using it and it makes profiling performance problems so much easier :-)

**Comment by dwilliamson** [comment]
Great, thanks. Is there any chance you can open a PR for this? I'm happy with the exter glXGetProcAddressARB solution for now. Final solution should really just include the correct headers.
