### ISSUE TITLE
Add ability to enable/disable Remotery via project settings

### ISSUE THREAD

**Issue by bkaradzic** [Celtoys/Remotery#64]
By default Remotery is always enabled because there is `#define RMT_ENABLED`. There is no way to change it without modifying code.

I propose change to:

```cpp
#ifndef RMT_ENABLED
#define RMT_ENABLED 1
#endif
```

With this, code should not use `#ifdefs` anymore, but rather `#if` because symbol will be always defined. This simplifies integration with other projects.

**Comment by dwilliamson** [comment]
OK, that makes a lot more sense that what I was thinking 173d3c778896c1e8cb4174b8924d9648e595bdd9

**Comment by bkaradzic** [comment]
Thanks! :+1:
