### ISSUE TITLE
glGetError and other OpenGL functions are statically linked

### ISSUE THREAD

**Issue by bkaradzic** [Celtoys/Remotery#68]
There are two issues in use of glGetError in Remotery.
1. It's statically linked, while all other functions are dynamically loaded.
   https://github.com/Celtoys/Remotery/blob/master/lib/Remotery.c#L5372
2. It's actually called. On some drivers/platforms glGetError is very costly operation, and it should be only optionally called. The best way to deal with it is to wrap all GL calls with GL(_call) macro that can turn on/off glGetError checking when necessary. Also it simplifies and make GL code cleaner. Here is example from my codebase: https://github.com/bkaradzic/bgfx/blob/master/src/renderer_gl.h#L839

This is my current workaround this issue (it fixes both :):
https://github.com/bkaradzic/bgfx/blob/master/3rdparty/remotery/lib/Remotery.c#L5372

**Comment by SoylentGraham** [comment]
Out of curiosity, which platforms is glGetError slow on?

**Comment by bkaradzic** [comment]
For example, extreme case is Native Client, where glGetError serializes GL client and server.

**Comment by dwilliamson** [comment]
This sounds good but I'm in the middle of Mexico right now and can't pull until we have a more stable internet connection. I'll get this through next week.

**Comment by dwilliamson** [comment]
OK, this isn't too much of an issue right now:

* On Windows, `glGetError` is linked if you can already call `wglGetProcAddress`.
* Native Client isn't hooked up to use OpenGL as its `rmtGetProcAddress` impl is empty.
* It's a much bigger problem. On Windows you still need to static link for `wglGetProcAddress`. There's also `glXGetProcAddressARB` and `NSGLGetProcAddress` which I have no idea about.

The whole thing does need a bit of a cleanup. HI'ow do you get around the `wglGetProcAddress` issue?

I'll open another issue for calls being slow as their complexities are very different.

**Comment by bkaradzic** [comment]
glGetError can be loaded with GetProcAddress.

**Comment by bkaradzic** [comment]
Btw, forgot to mention, the reason why I see this issue is because bgfx doesn't link with opengl32.lib (nor d3d9/11/etc.) at all. Everything is dynamically loaded.

**Comment by dwilliamson** [comment]
Yep, I get that. My game uses multiple DLLs and I want to be able to issue GPU samples outside of the graphics DLLs without linking to the graphics libraries.

Thanks for your help.

**Comment by dwilliamson** [comment]
Preliminary work on this https://github.com/Celtoys/Remotery/commit/1f2c46107048fd54e356b17014a17aabddc1853e

**Comment by bkaradzic** [comment]
What's wrong with GL in one change list. :)

**Comment by dwilliamson** [comment]
Only Linux left to fix now. Should be able to `dlopen` `libgl.so` by the looks of things: https://github.com/ApoorvaJ/Papaya/blob/3808e39b0f45d4ca4972621c847586e4060c042a/src/libs/gl_lite.h#L132

**Comment by dwilliamson** [comment]
Fixed in c66d2e8bebeb2bcf5710ee65fc94310b0c60ffdc
