### ISSUE TITLE
Integration proposal

### ISSUE THREAD

**Issue by araud** [Celtoys/Remotery#74]
Hi!

I would like to add Remotery support to this project: https://github.com/01org/IntelSEAPI/wiki
Please contact me to discuss details? alexander.a.raud at intel dot com

With respect, Alex.

**Comment by dwilliamson** [comment]
Hi Alex,

this sounds great. I'd like to discuss integration here, if you don't mind. The formatting and referencing tools are much better than email and it's also out in the open for others to benefit from.

What's on your mind?

Cheers,
-Don

**Comment by araud** [comment]
[Intel(R) Single Event API](https://github.com/01org/IntelSEAPI/wiki) is a format translator.
It takes itt_notify (open source cross platform pure C mark up interface) calls and generates different runtime (like ETW, ftrace, dtrace) and offline formats (like dot, json, btf) suitable for OS specific and third party trace viewers, like WPA, XCode Instruments, Chrome, QTCreator, GraphViz, Trace Compass (more are coming).
I would like to have Remotery viewer supported as well.
Plus, if you are interested, we can support Remotery API to itt_notify translation that will allow users to have runtime call graphs, for example.

I meant to talk via skype as it's hard to put much in text. If you write to my mail box (in first message) I will give you my skype id.

With respect, Alex.

**Comment by dwilliamson** [comment]
continued via email
