### ISSUE TITLE
Cannot compile the code in debian

### ISSUE THREAD

**Issue by alpha-xue** [Celtoys/Remotery#76]
Hi,
When I download the whole code repository and tried to compile it in my debian Linux server. I encounter following error:

```
The pwd is now under the home folder of Remotery-master.
linux1:/uac/msc/yfxue/www> cd Remotery-master/
linux1:/uac/msc/yfxue/www/Remotery-master> cc lib/Remotery.c sample/sample.c -l lib -p thread -lm
sample/sample.c:3:22: fatal error: Remotery.h: No such file or directory
compilation terminated.
linux1:/uac/msc/yfxue/www/Remotery-master> pwd
/uac/msc/yfxue/www/Remotery-master

linux1:/uac/msc/yfxue/www/Remotery-master> ls
./  ../  lib/  LICENSE*  readme.md*  sample/  screenshot.png*  vis/
linux1:/uac/msc/yfxue/www/Remotery-master> ls ./lib/
./  ../  Remotery.c*  Remotery.h*
```

Then I tried to copy  ./lib/Remotery.c to ./sample/ but it still failed as following:

```
yfxue@linux1:~/www/Remotery-master$ cp lib/Remotery.h ./sample/
yfxue@linux1:~/www/Remotery-master$  cc ./lib/Remotery.c ./sample/sample.c -l ./lib -pthread -lm
/usr/bin/ld: cannot find -l./lib
collect2: error: ld returned 1 exit status
```

```
Then I modifed my command as following, it error out also:
yfxue@linux1:~/www/Remotery-master$  cc lib/Remotery.c sample/sample.c -l lib -pthread -lm
/usr/bin/ld: cannot find -llib
collect2: error: ld returned 1 exit status
yfxue@linux1:~/www/Remotery-master$  cc lib/Remotery.c sample/sample.c  -pthread -lm
/tmp/ccy20F2Q.o: In function `rmtLoadLibrary':
Remotery.c:(.text+0x103): undefined reference to `dlopen'
/tmp/ccy20F2Q.o: In function `rmtFreeLibrary':
Remotery.c:(.text+0x11d): undefined reference to `dlclose'
/tmp/ccy20F2Q.o: In function `rmtGetProcAddress':
Remotery.c:(.text+0x142): undefined reference to `dlsym'
/tmp/ccy20F2Q.o: In function `usTimer_Init':
Remotery.c:(.text+0x1a2): undefined reference to `clock_gettime'
/tmp/ccy20F2Q.o: In function `usTimer_Get':
Remotery.c:(.text+0x21d): undefined reference to `clock_gettime'
collect2: error: ld returned 1 exit status
yfxue@linux1:~/www/Remotery-master$
```

My Linux version as following:

```
yfxue@linux1:~/www/Remotery-master$ cat /proc/version
Linux version 3.2.0-4-amd64 (debian-kernel@lists.debian.org) (gcc version 4.6.3 (Debian 4.6.3-14) ) 
#1 SMP Debian 3.2.63-2+deb7u2
```

I am not sure if it suitable for compile the whole code repository under this linux version or it requires some additional setup for running?

Thanks,

**Comment by alpha-xue** [comment]
Above is I switch shell to bash, whereas When I do not change the shell from default tcsh then it throw out:
 cc lib/Remotery.c sample/sample.c -I lib -pthread -lm
lib/Remotery.c:883: error: redefinition of typedef ‘Thread’
lib/Remotery.c:859: note: previous declaration of ‘Thread’ was here
lib/Remotery.c:886: error: redefinition of typedef ‘ThreadProc’
lib/Remotery.c:860: note: previous declaration of ‘ThreadProc’ was here

I guess this kind of code is ok for what error mentioned.

**Comment by dwilliamson** [comment]
OK, so the first problem is a pretty basic linker error. You need to find somebody in your university that can help you understand what's going on. Add these to your command-line:

```
-ldl -lrt
```

Answers to your questions found here:

http://stackoverflow.com/questions/956640/linux-c-error-undefined-reference-to-dlopen
http://stackoverflow.com/questions/17128773/undefined-reference-to-clock-gettime-in-linux-using-icc

**Comment by dwilliamson** [comment]
For the second, can you get latest and try compiling again?

https://github.com/Celtoys/Remotery/commit/a563c9272d5dea62c6d9a6a23fa811d95d98408f

**Comment by alpha-xue** [comment]
Sorry for late replay.
Yes. I use following command and it works fine now under tcsh.:
 cc lib/Remotery.c sample/sample.c -I  lib -pthread -lm -ldl -lrt

Thanks a lot for your input..
I am trying embed my code in order for it can work for the profiling.

Should I just need replace for loop as invoke my own code here? A little question here is that what is parameter 'delay' here?

    rmt_BeginCPUSample(delay);
    for( i = 0, end = rand()/100; i < end; ++i ) {
        j += sin(i);
    }
    rmt_EndCPUSample();

**Comment by dwilliamson** [comment]
`delay` is the name of your sample that will show up in Remotery. The parameter is documented in the header file.

PLEASE read the source code. You are sampling the CPU here and it looks like you want to sample CUDA.

I do not have time to help you with basic questions that you should be going to with your supervisor.

**Comment by alpha-xue** [comment]
I read the almost whole code, didn't find anywhere define delay.
Besides, variables  &cuCtxSetCurrent also did not find anywhere.
    bind.CtxSetCurrent = &cuCtxSetCurrent;
    bind.CtxGetCurrent = &cuCtxGetCurrent;
    bind.EventCreate = &cuEventCreate;
    bind.EventDestroy = &cuEventDestroy;
    bind.EventRecord = &cuEventRecord;
    bind.EventQuery = &cuEventQuery;
    bind.EventElapsedTime = &cuEventElapsedTime;

Now when I use them in my code, it cannot compile through.

**Comment by zao** [comment]
A key insight you need to understand [`rmt_BeginCPUSample`](https://github.com/Celtoys/Remotery/blob/master/lib/Remotery.h#L292) is that it's a macro, not a regular function. If you don't have any documentation, you have to read the definition of the macro to figure out how it's supposed to be used.

The two functions of the preprocessor used there that may be unfamiliar to a casual reader are the `#` _stringify_ operator and the `##` _token paste_ operator.

`#` takes the actual name of the macro argument and turns it into a string. `#name` where you pass `delay` as `name` ends up as the string literal `"delay"`.
`##` takes the two tokens on either side and joins them into a single token. `rmt_sample_hash_##name` ends up as the identifier `rmt_sample_hash_delay`.

It follows from this that `delay` in the example can be anything that can legally form an identifier and be passed as a macro argument. It will show up by that literal name in the trace output.

As for your `cu-` prefixed identifiers, those should come from your CUDA SDK. Ensure that you have the headers included where you use them. That's again something outside of the scope of this project as it's highly dependent on CUDA SDK version and how your project is structured.
