### ISSUE TITLE
Docs and sample do not match API.

### ISSUE THREAD

**Issue by stolk** [Celtoys/Remotery#79]
The docs and sample do not mention the flags parameter to rmt_BeginCPUSample() rmt_ScopedCPUSample().

Docs and sample could be out of date?

```
#define rmt_BeginCPUSample(name, flags)                                             \
    RMT_OPTIONAL(RMT_ENABLED, {                                                     \
        static rmtU32 rmt_sample_hash_##name = 0;                                   \
        _rmt_BeginCPUSample(#name, flags, &rmt_sample_hash_##name);                 \
    })
```

**Comment by amigo421** [comment]
I'm not an owner of the project , but from the sources , looks the flags should be one of these:
typedef enum rmtSampleFlags
{
    // Default behaviour
    RMTSF_None          = 0,

    // Search parent for same-named samples and merge timing instead of adding a new sample
    RMTSF_Aggregate     = 1,
} rmtSampleFlags;

**Comment by dwilliamson** [comment]
542e0b2558d45e7b9ccaa90d309d84ffcee9da0f and 407e1bf92139eb0c1d168967961e13c5319ef72e
