### ISSUE TITLE
type redefinition issue (build with MinGW64)

### ISSUE THREAD

**Issue by amigo421** [Celtoys/Remotery#80]
(not sure that is a really bug)
just tried to clone and use this in my project with mingw64,
only inlcuded c and h files into a project and took a sample code from an example 

Remotery.c:1068:22: error: conflicting types for 'rsize_t'
 typedef unsigned int rsize_t;
                      ^
In file included from C:/dev/tools/mingw/mingw64/x86_64-w64-mingw32/include/malloc.h:9:0,
                 from C:\dev\workspace\algolist\remotery\Remotery.c:93:
C:/dev/tools/mingw/mingw64/x86_64-w64-mingw32/include/crtdefs.h:52:16: note: previous declaration of 'rsize_t' was here
 typedef size_t rsize_t;
                ^

**Comment by dwilliamson** [comment]
I'm not sure how that's possible: is `__MINGW32__` defined?

**Comment by dwilliamson** [comment]
Yikes, that include path is... odd: `/mingw64/x86_64-w64-mingw32` - explains  it.

Can you see if `RSIZE_T` is defined in your `crtdefs.h` file?

**Comment by dwilliamson** [comment]
Nope it's `RSIZE_T_DEFINED` https://github.com/msys2/mingw-w64/blob/master/mingw-w64-headers/crt/crtdefs.h#L51

**Comment by dwilliamson** [comment]
85d7b25ca3a24a66c878b2b23da69f60335a11e7
