### ISSUE TITLE
intermittent assertion failure.

### ISSUE THREAD

**Issue by stolk** [Celtoys/Remotery#81]
I get this assertion failure, intermittently.
Some race-condition maybe?

Why it the destructor called when creating a global instance?

crowdsim: Remotery.c:4222: void Remotery_Destructor(Remotery *): Assertion `g_RemoteryCreated == ((rmtBool)1)' failed.
==7192== 
==7192== Process terminating with default action of signal 6 (SIGABRT): dumping core
==7192==    at 0x7A21267: raise (raise.c:55)
==7192==    by 0x7A22EC9: abort (abort.c:89)
==7192==    by 0x7A1A03C: __assert_fail_base (assert.c:92)
==7192==    by 0x7A1A0F1: __assert_fail (assert.c:101)
==7192==    by 0x40806F: Remotery_Destructor (Remotery.c:4222)
==7192==    by 0x407B56: _rmt_CreateGlobalInstance (Remotery.c:4373)
==7192==    by 0x41426D: ctrl_create(int, int, float) (ctrl.cpp:844)
==7192==    by 0x406701: main (sdlmain.cpp:479)

**Comment by Celtoys** [comment]
That happens on start up connection failure. Is another copy of the game still running?

**Comment by dwilliamson** [comment]
When there are errors during constructor calls, the object model attempts a tear down of the partially constructed object by calling the destructor; a requirement the destructor needs to be aware of.

**Comment by stolk** [comment]
Next time I see this, I will double check for a second game still running.
Thx.

On Thu, Mar 24, 2016 at 1:36 PM, Don Williamson <notifications@github.com>
wrote:

> When there are errors during constructor calls, the object model attempts
> a tear down of the partially constructed object by calling the destructor;
> a requirement the destructor needs to be aware of.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Celtoys/Remotery/issues/81#issuecomment-201007479>
>



-- 
Owner/Director of Game Studio Abraham Stolk Inc.
Vancouver BC, Canada
b.stolk@gmail.com

**Comment by stolk** [comment]
Happens without second copy of the game.

The error happens if I close my browser tab with the viz as well, before launching.

However, the error goes away if I kill my browser completely.

Maybe you need to look into lingering sockets: SO_LINGER, SO_REUSEADDR and stuff.

**Comment by dwilliamson** [comment]
What platform/browser is this? The C++ side is correctly (gracefully) closing connections so I suspect the browser may not be fulfilling its side of the deal.
