### ISSUE TITLE
Feedback: Reloading DLLs

### ISSUE THREAD

**Issue by uucidl** [Celtoys/Remotery#85]
I don't know where to put this, basically this is not an issue but a situation and its solution. Could go into a FAQ of sort.

In my case, I have a (private) program which uses C.Muratori's style of reloading an user code DLL automatically on recompilation.

When reloading that DLL dynamically, Remotery's message queue needs to be empty before unloading the DLL. Otherwise when this happens, Remotery crashes in:
```
 	playground_dev.exe!strnlen_s_safe_c(const char * dest, unsigned __int64 dmax) Line 1109	C++
 	playground_dev.exe!Buffer_WriteString(Buffer * buffer, const char * string) Line 1614	C++
 	playground_dev.exe!json_String(Buffer * buffer, const char * string) Line 3259	C++
 	playground_dev.exe!json_FieldStr(Buffer * buffer, const char * name, const char * value) Line 3270	C++
 	playground_dev.exe!json_Sample(Buffer * buffer, Sample * sample) Line 3437	C++
 	playground_dev.exe!json_SampleArray(Buffer * buffer, Sample * first_sample, const char * name) Line 3467	C++
 	playground_dev.exe!json_Sample(Buffer * buffer, Sample * sample) Line 3450	C++
 	playground_dev.exe!json_SampleArray(Buffer * buffer, Sample * first_sample, const char * name) Line 3467	C++
 	playground_dev.exe!json_Sample(Buffer * buffer, Sample * sample) Line 3450	C++
 	playground_dev.exe!json_SampleArray(Buffer * buffer, Sample * first_sample, const char * name) Line 3467	C++
 	playground_dev.exe!json_SampleTree(Buffer * buffer, Msg_SampleTree * msg) Line 3972	C++
>	playground_dev.exe!Remotery_SendSampleTreeMessage(Remotery * rmt, Message * message) Line 4023	C++
 	playground_dev.exe!Remotery_ConsumeMessageQueue(Remotery * rmt) Line 4065	C++
 	playground_dev.exe!Remotery_ThreadMain(Thread * thread) Line 4128	C++
```
My guess is that the litterals generated by the traces on the DLL side disappeared when the dll got unloaded (using `FreeLibrary`)

The solution is to destroy and recreate the main remotery instance, rebinding any opengl or d3d functions etc... around the DLL reloading. So:
```
rmt_UnbindOpenGL();
rmt_DestroyGlobalInstance(rmt);
FreeLibrary(dll);
dll = LoadLibraryA(b);
fatal_ifnot(RMT_ERROR_NONE == rmt_DestroyGlobalInstance(&rmt));
rmt_BindOpenGL();
```

**Comment by dwilliamson** [comment]
I could potentially fix this. The first time a sample is encountered it will calculate the hash. It would cost nothing to copy the sample name at the same time.

**Comment by dwilliamson** [comment]
I have a fix in one of my branches, will land soon.

**Comment by uucidl** [comment]
Exciting :) I can test it once it's available

**Comment by dwilliamson** [comment]
Fixed in https://github.com/Celtoys/Remotery/commit/a9e86015538a7c630ba39879fc12e136a327de28

**Comment by uucidl** [comment]
:+1:
