### ISSUE TITLE
Linux: #define _POSIX_C_SOURCE 199309L doesn't work

### ISSUE THREAD

**Issue by DanielGibson** [Celtoys/Remotery#88]
It has several problems:
1. you get redefinition warnings when compiling in gnu mode
2. it needs to be done even earlier, *before* including `malloc.h` and `assert.h`
3. some functions, like `usleep()` `FD_ZERO` etc are still not found then..
4. .. `#define _GNU_SOURCE` instead fixes the missing function definitions
5. ... but even then gcc (4.8) and clang (3.8.0) complain about `undeclared identifier 'asm'`, from `asm volatile ("" : : : "memory");`

So I guess making Remotery compile on Linux with `-std=c99` just doesn't work - I'd suggest removing that define and expecting people to use `std=gnu89` or gnu99 or gnu11 or whatever.
I doubt you can write meaningful software without that anyway (maybe parts of software, but there will be other more system-specific parts, and remotery.c would just be that kind of part part then).
Furthermore, gcc uses gnu89 as default and clang gnu99 (IIRC), so people will only run into problems when explicitly setting c99 (or c11) anyway.

**Comment by dwilliamson** [comment]
I have users who supposedly use `-std=c99` but not many people stick around long enough to work through a full feedback loop.

AFAICS there is just one error up there preventing it working in C99 mode?

**Comment by DanielGibson** [comment]
If you remove `#define _POSIX_C_SOURCE ...` and instead `#define _GNU_SOURCE` before the first #include (I think that's currently `#include malloc.h` which really shouldn't be needed on Linux or even FreeBSD anyway, malloc etc are in stdlib.h), the only error  when compiling with `-std=c99` is about `asm volatile ("" : : : "memory");` in `WriteFence()`.

But I really don't think it's too much of a burden to ask people to compile it in gnu C mode instead of strict C mode.

**Comment by dwilliamson** [comment]
This was the original issue which I didn't actually completely fix (forgot about `asm`) https://github.com/Celtoys/Remotery/issues/78

This guy never stuck around to answer many of my questions so maybe there is little worth it preserving this.

**Comment by DanielGibson** [comment]
Yeah, apparently he was the only one with that problem an didn't even notice/report your fix didn't really fix it so.. just document it needs -std=gnu* on Linux (and that it's the default).
People complaining about that and insisting on building with -std=c99 (whichs purpose is undermined by that #define) probably don't know what they're doing anyway ;-)
