### ISSUE TITLE
When Zooming on timeline, show sub tasks?

### ISSUE THREAD

**Issue by TrianglesPCT** [Celtoys/Remotery#89]
This is a feature request, actually perhaps I'll try doing it myself, not sure, haven't looked at how Remotery visualization works yet.

 On the timeline if I have nested tasks, it will only show the outer task, I'll like it if when paused, and I zoom in, it would show the sub tasks.

I have so many threads running that they don't fit on my windows in the thread view under the timeline. This means when I look at a task on timeline I often can't see the sub tasks because that task isn't visible as it didn't fit on screen.

Thanks!

**Comment by dwilliamson** [comment]
If I understand you correctly, this is exactly what the +/- buttons on the left are for.

Can you confirm this?

**Comment by TrianglesPCT** [comment]
Ah! Yes that is exactly what I wanted! Sorry I did not know the + button did that. 
Thanks
