### ISSUE TITLE
'unreferenced formal parameter' C4100 in Release build (VS 2015)

### ISSUE THREAD

**Issue by samswain** [Celtoys/Remotery#94]
In a release/shipping build the assert call is compiled away and the warning returns.

`#define RMT_UNREFERENCED_PARAMETER(i) assert(i == 0 || i != 0);    // To fool warning C4100 on warning level 4`

The [MSN docs](https://msdn.microsoft.com/en-us/library/26kb9fy0.aspx) suggest just using the parameter in an expression.  This seems to work in VS2015, but I'm not able to try in other scenarios.

`#define RMT_UNREFERENCED_PARAMETER(i) i    // To fool warning C4100 on warning level 4`

Oddly, the non-MSC version of the macro doesn't seem sufficient.

**Comment by dwilliamson** [comment]
I hate this. Keeps coming back to bite me.

Until I get a CI build for all the major compilers I'm not going to address this issue yet!

**Comment by Celtoys** [comment]
Fixed in 978ce09bdb0448ba5de6e26577cf0332bd5ea047
