### ISSUE TITLE
iOS/OSX ::bind compile error

### ISSUE THREAD

**Issue by jazzbre** [Celtoys/Remotery#97]
`/../../source/third_party/Remotery/lib/Remotery.c:2146:9: fatal error: expected expression
    if (::bind(s, (struct sockaddr*)&sin, sizeof(sin)) == SOCKET_ERROR)
`

If I change the ::bind to bind it works ok. This is with Xcode 8.0 beta 2, so It is possible that it works with previous versions, but don't have time to reinstall right now.

**Comment by zao** [comment]
There's a fix for this in pull request #96, which doesn't seem to be merged yet.
The change you've made is correct.

**Comment by dwilliamson** [comment]
I'm behind on PRs right now. Will catch up soon.

**Comment by mgerhardy** [comment]
Sorry, I've reported a duplicate #100 - but a fix is included there, too.
